
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuawjzdnuwejvbrmrjoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1YXdqemRudXdlanZicm1yam9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzY4NTMsImV4cCI6MjA1NjQxMjg1M30.F0CYov7fc_7trDip1Cr_1GB0OeRFEAaXVHQknwJCfQM";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
